changeLogFile=./changelog.xml
driver=com.mysql.cj.jdbc.Driver
classpath= /home/vivek/liquibase-temp/mysql-connector-j-8.3.0.jar
url=jdbc:mysql://localhost:3306/SeaBasket
username=root
password=Cap@70098

